CREATE_USER_TABLE_QUERY = """
CREATE TABLE IF NOT EXISTS telegram_users
(
ID INTEGER PRIMARY KEY AUTOINCREMENT,
TELEGRAM_ID INTEGER,
USERNAME CHAR(50),
FIRST_NAME CHAR(50),
LAST_NAME CHAR(50),
UNIQUE (TELEGRAM_ID)
)
"""
CREATE_QUESTIONNAIRE_TABLE_QUERY = """
CREATE TABLE IF NOT EXISTS questionnaire_profile(
ID INTEGER PRIMARY KEY,
TELEGRAM_ID INTEGER,
IDEA TEXT,
PROBLEMS TEXT,
UNIQUE (ID))
"""
CREATE_BAN_USER_TABLE_QUERY = """
CREATE TABLE IF NOT EXISTS ban_users
(
ID INTEGER PRIMARY KEY AUTOINCREMENT,
TELEGRAM_ID INTEGER,
COUNT INTEGER,
UNIQUE (TELEGRAM_ID)
)
"""
CREATE_USER_PROFILE_QUERY = """
CREATE TABLE IF NOT EXISTS user_profile
(
ID INTEGER PRIMARY KEY AUTOINCREMENT,
TELEGRAM_ID INTEGER,
NICKNAME CHAR(50),
AGE INTEGER,
SEX CHAR (50),
BIOGRAPHY CHAR(50),
GEOLOCATION CHAR(50),
PHOTO TEXT,
UNIQUE (TELEGRAM_ID)
)
"""

INSERT_USER_QUERY = """
INSERT INTO telegram_users VALUES (?, ?, ?, ?, ?)
"""

INSERT_QUESTIONNAIRE_QUERY = """
INSERT INTO questionnaire_profile (TELEGRAM_ID, IDEA, PROBLEMS) VALUES (?, ?, ?)
"""

INSERT_BAN_USER_QUERY = """
INSERT INTO ban_users VALUES (?, ?, ?)"""

SELECT_BAN_USER_QUERY = """
SELECT * FROM ban_users WHERE TELEGRAM_ID = ?
"""

UPDATE_BAN_USER_COUNT_QUERY = """
UPDATE ban_users SET COUNT = COUNT + 1 WHERE TELEGRAM_ID = ?
"""
INSERT_USER_PROFILE_QUERY = """
INSERT INTO user_profile VALUES (?, ?, ?, ?, ?, ?, ?, ?)
"""

SELECT_USER_PROFILE_QUERY = """
SELECT * FROM user_profile WHERE ID = ?"""
